version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-api
    container_name: laravel_app
    volumes:
      - .:/var/www
    depends_on:
      - db
    networks:
      - laravel

  db:
    image: postgres:15
    container_name: postgres_db
    ports:
      - '${FORWARD_DB_PORT:-5432}:5432'
    restart: always
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata1:/var/lib/postgresql/data
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    ports:
      - 8000:80
    volumes:
      - .:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d/
    depends_on:
      - app
    networks:
      - laravel

volumes:
  pgdata1:

networks:
  laravel:
    driver: bridge
